import os
from dotenv import load_dotenv
from google import genai
from flask import Flask, render_template, request, jsonify, send_from_directory
from werkzeug.utils import secure_filename
from predictor import analyze_image, analyze_soil, analyze_fertilizer

app = Flask(__name__)

@app.route('/sw.js')
def sw():
    return send_from_directory('.', 'sw.js', mimetype='application/javascript')
# Maximum upload size: 16 MB
app.config['MAX_CONTENT_LENGTH'] = 16 * 1024 * 1024  
# Configure upload folder
UPLOAD_FOLDER = 'uploads'
os.makedirs(UPLOAD_FOLDER, exist_ok=True)
app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER

ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'webp'}

def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/about')
def about():
    return render_template('about.html')

@app.route('/chat', methods=['POST'])
def chat():
    data = request.get_json()
    user_question = data.get('message', data.get('question', ''))
    context = data.get('context', '') # disease context from frontend
    lang = data.get('lang', 'English')
    
    if not user_question:
        return jsonify({'error': 'No question provided'}), 400
    
    try:
        load_dotenv(override=True)
        api_key = os.getenv("GEMINI_API_KEY")
        client = genai.Client(api_key=api_key)
        
        prompt = f"""You are an expert agricultural consultant AI assistant for an app called AgriLens.
        
The user has just scanned a crop leaf and the diagnosis was:
{context}

The user now has a follow-up question: "{user_question}"

Answer the question concisely and helpfully, focusing on practical advice for a farmer. Keep the response to 2-3 sentences maximum.
IMPORTANT: You MUST reply entirely in the {lang} language. Translate everything to {lang}.
If the user asks for an example image or picture, you MUST include it dynamically using this markdown syntax: `![{lang} Image Description](https://image.pollinations.ai/prompt/{{descriptive_english_prompt_with_underscores_instead_of_spaces}}?width=800&height=600)`. Example: `![{lang} image](https://image.pollinations.ai/prompt/red_soil_farm_india?width=800&height=600)`"""

        response = client.models.generate_content(model='gemini-2.5-flash', contents=prompt)
        return jsonify({'success': True, 'reply': response.text.strip()})
    except Exception as e:
        print(f"Chat error: {e}")
        return jsonify({'success': False, 'reply': f"Sorry, I couldn't connect to the AI right now. Error: {str(e)}"})

@app.route('/crop-chat', methods=['POST'])
def crop_chat():
    data = request.get_json()
    user_message = data.get('message', '')
    lang = data.get('lang', 'English')
    if not user_message:
        return jsonify({'error': 'No message provided'}), 400
    try:
        load_dotenv(override=True)
        api_key = os.getenv("GEMINI_API_KEY")
        client = genai.Client(api_key=api_key)
        system_prompt = f"""You are AgriBot, an expert AI agricultural advisor specialized in Indian farming.
You have deep knowledge of:
- Crop planning, rotation, and seasonal calendars for different Indian states
- Soil types (sandy, loamy, clay, red, black soil) and their suitability for crops
- Fertilizers (NPK, organic, micronutrients) and application schedules
- Irrigation techniques (drip, flood, sprinkler)
- Government schemes like PM-Kisan, Pradhan Mantri Fasal Bima Yojana
- Market prices, MSP, and profit optimization for Indian farmers
- Indian states and districts: Andhra Pradesh, Telangana, Karnataka, Tamil Nadu, Maharashtra, Punjab, etc.

Always respond in a friendly, encouraging, and simple manner suitable for farmers.
Format your responses with clear sections when needed. Use bullet points for lists.
User's question: {user_message}
Provide a practical, helpful answer specific to Indian farming context.
IMPORTANT: You MUST reply entirely in the {lang} language. Translate everything to {lang}.
If the user asks for an example image or picture, you MUST include it dynamically using this markdown syntax: `![{lang} Image Description](https://image.pollinations.ai/prompt/{{descriptive_english_prompt_with_underscores_instead_of_spaces}}?width=800&height=600)`. Example: `![{lang} image](https://image.pollinations.ai/prompt/farming_tractor_in_field_india?width=800&height=600)`"""
        response = client.models.generate_content(model='gemini-2.5-flash', contents=system_prompt)
        return jsonify({'success': True, 'reply': response.text.strip()})
    except Exception as e:
        print(f"Crop-chat error: {e}")
        return jsonify({'success': False, 'reply': f"Sorry, AgriBot couldn't connect right now. Error: {str(e)}"})

@app.route('/knowledge')
def knowledge():
    # The database was dynamically generated by AI now, so we render a notice
    # or just an empty template if the user clicks it.
    return render_template('knowledge.html', diseases={})


@app.route('/weather', methods=['POST'])
def weather():
    data = request.get_json()
    location = data.get('location', '')
    lang = data.get('lang', 'English')
    coords = data.get('coords', None)
    if not location:
        return jsonify({'error': 'No location provided'}), 400
    try:
        load_dotenv(override=True)
        api_key = os.getenv("GEMINI_API_KEY")
        client = genai.Client(api_key=api_key)
        
        location_info = location
        if coords:
            location_info = f"latitude {coords['lat']}, longitude {coords['lon']}"
        prompt = f"You are an expert AI agricultural meteorologist. The user is asking for local weather advice for farming in '{location_info}'. Provide a short 3-4 sentence practical weather-based farming advice for this location right now. Keep it concise, and tailored to Indian farming if the location is in India. IMPORTANT: You MUST reply entirely in {lang} language."
        response = client.models.generate_content(model='gemini-2.5-flash', contents=prompt)
        return jsonify({'success': True, 'reply': response.text.strip()})
    except Exception as e:
        print(f"Weather error: {e}")
        return jsonify({'success': False, 'reply': f"Sorry, could not connect to Weather AI right now. Error: {str(e)}"})

@app.route('/market', methods=['POST'])
def market():
    data = request.get_json()
    crop = data.get('crop', '')
    lang = data.get('lang', 'English')
    coords = data.get('coords', None)
    if not crop:
        return jsonify({'error': 'No crop provided'}), 400
    try:
        load_dotenv(override=True)
        api_key = os.getenv("GEMINI_API_KEY")
        client = genai.Client(api_key=api_key)
        
        location_info = "the local region"
        if coords:
            location_info = f"the region at latitude {coords['lat']}, longitude {coords['lon']}"
        prompt = f"You are an expert AI agricultural economist. The user wants to know the current market price trend and advice for the crop: {crop} in {location_info}. Provide a concise 3-4 sentence market analysis, simulated realistic price trend (in INR/Quintal), and advice on whether to sell or hold. Keep it highly practical for an Indian farmer. IMPORTANT: You MUST reply entirely in {lang} language."
        response = client.models.generate_content(model='gemini-2.5-flash', contents=prompt)
        return jsonify({'success': True, 'reply': response.text.strip()})
    except Exception as e:
        print(f"Market error: {e}")
        return jsonify({'success': False, 'reply': f"Sorry, could not connect to Market AI right now. Error: {str(e)}"})

@app.route('/calendar_schedule', methods=['POST'])
def calendar_schedule():
    data = request.get_json()
    crop = data.get('crop', '')
    date = data.get('date', '')
    lang = data.get('lang', 'English')
    
    if not crop or not date:
        return jsonify({'error': 'Missing crop or date'}), 400
        
    try:
        import json
        load_dotenv(override=True)
        api_key = os.getenv("GEMINI_API_KEY")
        client = genai.Client(api_key=api_key)
        
        prompt = f"""You are an expert AI agricultural planner. The user wants to plant the crop '{crop}' starting on the date '{date}'.
Generate a complete timeline of tasks from planting to harvesting.
IMPORTANT: You MUST reply entirely in the {lang} language (except for JSON keys).

Return ONLY a raw JSON object string with this exact schema (no markdown blocks, no extra text):
{{
    "timeline": [
        {{"date": "calculated date based on {date}", "stage": "Stage Name", "task": "Detailed description of what to do (fertilizer, watering, etc)"}},
        {{"date": "next calculated date", "stage": "Next Stage", "task": "Description of next task"}}
    ]
}}
Ensure there are at least 5-8 chronological stages."""
        
        response = client.models.generate_content(
            model='gemini-2.5-flash', 
            contents=prompt,
            config=genai.types.GenerateContentConfig(temperature=0.2)
        )
        
        response_text = response.text.strip()
        if response_text.startswith("```json"): response_text = response_text[7:-3].strip()
        elif response_text.startswith("```"): response_text = response_text[3:-3].strip()
            
        schedule = json.loads(response_text)
        return jsonify({'success': True, 'timeline': schedule.get('timeline', [])})
    except Exception as e:
        print(f"Calendar error: {e}")
        return jsonify({'success': False, 'error': str(e)})

@app.route('/equipment_advisor', methods=['POST'])
def equipment_advisor():
    data = request.get_json()
    size = data.get('size', '')
    crop = data.get('crop', '')
    lang = data.get('lang', 'English')
    
    if not size or not crop:
        return jsonify({'error': 'Missing size or crop'}), 400
        
    try:
        import json
        load_dotenv(override=True)
        api_key = os.getenv("GEMINI_API_KEY")
        client = genai.Client(api_key=api_key)
        
        prompt = f"""You are an expert AI agricultural engineer and economist. The user has a farm of size '{size}' and is growing '{crop}'.
Recommend specific machinery (tractors, tillers, harvesters, smart irrigation) appropriate for this scale. Include whether they should buy or rent, and approximate market costs.
IMPORTANT: You MUST reply entirely in the {lang} language. Translate everything to {lang}.
Return ONLY a valid JSON object with the following schema:
{{
    "recommendations": [
        {{"machine": "Name of Machine", "action": "Buy or Rent?", "cost_estimate": "approx cost (in INR/USD)", "reason": "Why this fits their '{size}' farm"}}
    ],
    "summary": "Overall 2-sentence advice"
}}"""
        response = client.models.generate_content(model='gemini-2.5-flash', contents=prompt, config=genai.types.GenerateContentConfig(temperature=0.2))
        res_text = response.text.strip()
        if res_text.startswith("```json"): res_text = res_text[7:-3].strip()
        elif res_text.startswith("```"): res_text = res_text[3:-3].strip()
        return jsonify({'success': True, 'data': json.loads(res_text)})
    except Exception as e:
        return jsonify({'success': False, 'error': str(e)})

@app.route('/profit_calculator', methods=['POST'])
def profit_calculator():
    data = request.get_json()
    crop = data.get('crop', '')
    area = data.get('area', '')
    yield_est = data.get('yield_est', '')
    lang = data.get('lang', 'English')
    
    if not crop or not area or not yield_est:
        return jsonify({'error': 'Missing inputs'}), 400
        
    try:
        import json
        load_dotenv(override=True)
        api_key = os.getenv("GEMINI_API_KEY")
        client = genai.Client(api_key=api_key)
        
        prompt = f"""You are an expert AI agricultural economist. Create a highly detailed cost vs. revenue estimation for growing '{crop}' on '{area}' of land, with an expected yield of '{yield_est}'.
Provide realistic market numbers using Indian Rupees (INR) for costs like seeds, labor, fertilizer, and current market selling prices.
IMPORTANT: You MUST reply entirely in the {lang} language.
Return ONLY a valid JSON object with the following schema:
{{
    "costs": [
        {{"category": "e.g., Seeds", "amount": "Cost in INR"}},
        {{"category": "e.g., Labor", "amount": "Cost in INR"}}
    ],
    "total_cost": "Total cost string",
    "expected_revenue": "Gross revenue string",
    "profit_margin": "Net profit string and percentage",
    "advice": "1 sentence advice"
}}"""
        response = client.models.generate_content(model='gemini-2.5-flash', contents=prompt, config=genai.types.GenerateContentConfig(temperature=0.2))
        res_text = response.text.strip()
        if res_text.startswith("```json"): res_text = res_text[7:-3].strip()
        elif res_text.startswith("```"): res_text = res_text[3:-3].strip()
        return jsonify({'success': True, 'data': json.loads(res_text)})
    except Exception as e:
        return jsonify({'success': False, 'error': str(e)})

@app.route('/gov_schemes', methods=['POST'])
def gov_schemes():
    data = request.get_json()
    state = data.get('state', '')
    crop = data.get('crop', 'General')
    cat = data.get('cat', 'Small/Marginal')
    lang = data.get('lang', 'English')
    
    try:
        import json
        load_dotenv(override=True)
        api_key = os.getenv("GEMINI_API_KEY")
        client = genai.Client(api_key=api_key)
        
        prompt = f"""You are an AI expert on Indian agricultural law and subsidies. Find 3-4 highly relevant government schemes for a '{cat}' farmer in '{state}' growing '{crop}'.
IMPORTANT: You MUST reply entirely in the {lang} language.
Return ONLY a valid JSON object with the following schema:
{{
    "schemes": [
        {{"scheme_name": "Exact Scheme Name", "benefits": "What they get", "eligibility": "Who can apply", "how_to_apply": "Short URL or instruction"}}
    ]
}}"""
        response = client.models.generate_content(model='gemini-2.5-flash', contents=prompt, config=genai.types.GenerateContentConfig(temperature=0.2))
        res_text = response.text.strip()
        if res_text.startswith("```json"): res_text = res_text[7:-3].strip()
        elif res_text.startswith("```"): res_text = res_text[3:-3].strip()
        return jsonify({'success': True, 'data': json.loads(res_text)})
    except Exception as e:
        return jsonify({'success': False, 'error': str(e)})

@app.route('/pest_warning', methods=['POST'])
def pest_warning():
    data = request.get_json()
    coords = data.get('coords', None)
    lang = data.get('lang', 'English')
    
    if not coords:
        return jsonify({'success': False, 'warning': None})
        
    try:
        load_dotenv(override=True)
        api_key = os.getenv("GEMINI_API_KEY")
        client = genai.Client(api_key=api_key)
        
        prompt = f"""You are a predictive agricultural AI. Based on the coordinates {coords['lat']}, {coords['lon']}, what are the immediate seasonal pest or fungal risks for crops right now?
If there is a high risk, write a single highly urgent, practical warning string. If low risk, just reply with 'LOW_RISK'.
IMPORTANT: You MUST reply entirely in the {lang} language (unless it is exactly 'LOW_RISK')."""
        response = client.models.generate_content(model='gemini-2.5-flash', contents=prompt, config=genai.types.GenerateContentConfig(temperature=0.2))
        res_text = response.text.strip()
        if "LOW_RISK" in res_text.upper():
            return jsonify({'success': True, 'warning': None})
        return jsonify({'success': True, 'warning': res_text})
    except Exception as e:
        return jsonify({'success': False, 'error': str(e)})

@app.route('/predict', methods=['POST'])
def predict():
    if 'file' not in request.files:
        return jsonify({'error': 'No file part'}), 400
    
    file = request.files['file']
    
    if file.filename == '':
        return jsonify({'error': 'No selected file'}), 400
        
    if file and allowed_file(file.filename):
        filename = secure_filename(file.filename)
        filepath = os.path.join(app.config['UPLOAD_FOLDER'], filename)
        file.save(filepath)
        
        # Run True AI analysis (internet connected, dynamic generation)
        lang = request.form.get('lang', 'English')
        analysis_result = analyze_image(filepath, lang=lang)
        
        if not analysis_result.get('success'):
            exact_error = analysis_result.get('error', 'Unknown AI Error')
            print(f"--- PREDICTION FAILED --- Error: {exact_error}")
            return jsonify({'error': f"AI Error: {exact_error}"}), 500
            
        prediction_name = analysis_result['prediction']
        confidence = analysis_result['confidence']
        detected_crop = analysis_result.get('detected_crop', 'Unknown')
        
        # Get the dynamically generated details straight from the AI's mind
        disease_details = analysis_result.get('disease_details', {})
        disease_details['crop'] = detected_crop # Ensure UI shows the dynamically detected crop
        
        # Format the display name if healthy
        if prediction_name == "Healthy":
            display_name = "No Disease Detected"
        else:
            display_name = prediction_name
            
        print(f"Image analyzed: {filename}")
        print(f"Detected Crop: {detected_crop}")
        print(f"Detected Disease: {display_name} ({confidence}%)")
        
        # Respond with JSON data to the frontend
        return jsonify({
            'success': True,
            'prediction': display_name,
            'confidence': confidence,
            'disease_details': disease_details,
            'image_url': f'/uploads/{filename}'
        })
        
    return jsonify({'error': 'Invalid file type. Please upload a JPG or PNG image.'}), 400

@app.route('/analyze-soil', methods=['POST'])
def predict_soil():
    if 'file' not in request.files:
        return jsonify({'error': 'No file part'}), 400
    
    file = request.files['file']
    
    if file.filename == '':
        return jsonify({'error': 'No selected file'}), 400
        
    if file and allowed_file(file.filename):
        filename = secure_filename(file.filename)
        filepath = os.path.join(app.config['UPLOAD_FOLDER'], filename)
        file.save(filepath)
        
        # Run True AI analysis (internet connected, dynamic generation)
        lang = request.form.get('lang', 'English')
        analysis_result = analyze_soil(filepath, lang=lang)
        
        if not analysis_result.get('success'):
            exact_error = analysis_result.get('error', 'Unknown AI Error')
            print(f"--- SOIL_ANALYSIS FAILED --- Error: {exact_error}")
            return jsonify({'error': f"AI Error: {exact_error}"}), 500
            
        prediction_name = analysis_result['prediction']
        confidence = analysis_result['confidence']
        detected_crop = analysis_result.get('detected_crop', 'Unknown')
        
        # Get the dynamically generated details straight from the AI's mind
        disease_details = analysis_result.get('disease_details', {})
        disease_details['crop'] = detected_crop # Ensure UI shows the dynamically detected crop
        
        # Format the display name if healthy
        if prediction_name == "Healthy":
            display_name = "No Disease Detected"
        else:
            display_name = prediction_name
            
        print(f"Image analyzed: {filename}")
        print(f"Detected Crop: {detected_crop}")
        print(f"Detected Disease: {display_name} ({confidence}%)")
        
        # Respond with JSON data to the frontend
        return jsonify({
            'success': True,
            'prediction': display_name,
            'confidence': confidence,
            'disease_details': disease_details,
            'image_url': f'/uploads/{filename}'
        })
        
    return jsonify({'error': 'Invalid file type. Please upload a JPG or PNG image.'}), 400


@app.route('/analyze-fertilizer', methods=['POST'])
def predict_fertilizer():
    if 'file' not in request.files:
        return jsonify({'error': 'No file part'}), 400
    
    file = request.files['file']
    
    if file.filename == '':
        return jsonify({'error': 'No selected file'}), 400
        
    if file and allowed_file(file.filename):
        filename = secure_filename(file.filename)
        filepath = os.path.join(app.config['UPLOAD_FOLDER'], filename)
        file.save(filepath)
        
        # Run True AI analysis (internet connected, dynamic generation)
        lang = request.form.get('lang', 'English')
        analysis_result = analyze_fertilizer(filepath, lang=lang)
        
        if not analysis_result.get('success'):
            exact_error = analysis_result.get('error', 'Unknown AI Error')
            print(f"--- FERTILIZER_OCR FAILED --- Error: {exact_error}")
            return jsonify({'error': f"AI Error: {exact_error}"}), 500
            
        prediction_name = analysis_result['prediction']
        confidence = analysis_result['confidence']
        detected_crop = analysis_result.get('detected_crop', 'Unknown')
        
        # Get the dynamically generated details straight from the AI's mind
        disease_details = analysis_result.get('disease_details', {})
        disease_details['crop'] = detected_crop # Ensure UI shows the dynamically detected crop
        
        # Format the display name if healthy
        if prediction_name == "Healthy":
            display_name = "No Disease Detected"
        else:
            display_name = prediction_name
            
        print(f"Image analyzed: {filename}")
        print(f"Detected Crop: {detected_crop}")
        print(f"Detected Disease: {display_name} ({confidence}%)")
        
        # Respond with JSON data to the frontend
        return jsonify({
            'success': True,
            'prediction': display_name,
            'confidence': confidence,
            'disease_details': disease_details,
            'image_url': f'/uploads/{filename}'
        })
        
    return jsonify({'error': 'Invalid file type. Please upload a JPG or PNG image.'}), 400


@app.route('/uploads/<name>')
def download_file(name):
    return send_from_directory(app.config["UPLOAD_FOLDER"], name)

if __name__ == '__main__':
    # Run the Flask app
    print("Starting AI Crop Disease Detector (Dynamic GenAI Mode)")
    print("Open http://localhost:5000 in your browser")
    app.run(debug=True, host='0.0.0.0', port=5000)
