import re

with open('templates/index.html', 'r', encoding='utf-8') as f:
    html = f.read()

pattern = re.compile(r'(<!-- Disease Detection Section.*?)(?=<!-- Crop Planning Chatbot Section)', re.DOTALL)
match = pattern.search(html)

if match:
    disease_html = match.group(1)
    
    # Create Soil Section
    soil_html = disease_html.replace('Disease Detection Mode', 'Soil Analyzer Mode')
    soil_html = soil_html.replace('disease-mode-section', 'soil-mode-section')
    soil_html = soil_html.replace('fa-microscope', 'fa-mound')
    soil_html = soil_html.replace('Detect Crop Diseases', 'Analyze Soil Health')
    soil_html = soil_html.replace('Upload a photo of a crop leaf and our AI will instantly identify the disease', 'Upload a photo of your farm soil and our AI will detect moisture, composition, and recommend crops')
    soil_html = soil_html.replace('drop-zone', 'soil-drop-zone')
    soil_html = soil_html.replace('upload-form', 'soil-upload-form')
    soil_html = soil_html.replace('file-input', 'soil-file-input')
    soil_html = soil_html.replace('default-state', 'soil-default-state')
    soil_html = soil_html.replace('preview-state', 'soil-preview-state')
    soil_html = soil_html.replace('image-preview', 'soil-image-preview')
    soil_html = soil_html.replace('remove-btn', 'soil-remove-btn')
    soil_html = soil_html.replace('analyze-btn', 'soil-analyze-btn')
    soil_html = soil_html.replace('loading-overlay', 'soil-loading-overlay')
    soil_html = soil_html.replace('loading-status-text', 'soil-loading-status-text')
    soil_html = soil_html.replace('results-section', 'soil-results-section')
    soil_html = soil_html.replace('Scan New Leaf', 'Scan New Soil')
    soil_html = soil_html.replace('scan-new-btn', 'soil-scan-new-btn')
    soil_html = soil_html.replace('result-card-image', 'soil-result-card-image')
    soil_html = soil_html.replace('result-image', 'soil-result-image')
    soil_html = soil_html.replace('conf-value', 'soil-conf-value')
    soil_html = soil_html.replace('conf-bar', 'soil-conf-bar')
    soil_html = soil_html.replace('health-score', 'soil-health-score')
    soil_html = soil_html.replace('data-card', 'soil-data-card')
    soil_html = soil_html.replace('disease-name', 'soil-type-name')
    soil_html = soil_html.replace('crop-tag', 'soil-crop-tag')
    soil_html = soil_html.replace('scientific-name', 'soil-scientific-name')
    soil_html = soil_html.replace('severity-badge', 'soil-severity-badge')
    soil_html = soil_html.replace('Drag & Drop Leaf Image', 'Drag & Drop Soil Image')
    soil_html = soil_html.replace('<span class="mode-label">', '<span class="mode-label mode-label-orange">')
    soil_html = soil_html.replace('Symptoms', 'Visual Characteristics')
    soil_html = soil_html.replace('symptoms-text', 'soil-characteristics-text')
    soil_html = soil_html.replace('Causes', 'Composition Analysis')
    soil_html = soil_html.replace('causes-text', 'soil-composition-text')
    soil_html = soil_html.replace('Prevention', 'Recommended Crops')
    soil_html = soil_html.replace('prevention-text', 'soil-crops-text')
    soil_html = soil_html.replace('Treatment & Best Practices', 'Soil Improvement Strategies')
    soil_html = soil_html.replace('treatment-text', 'soil-treatment-text')
    soil_html = soil_html.replace('Recommended Chemical Control', 'Recommended Fertilizers')
    soil_html = soil_html.replace('chemicals-list', 'soil-fertilizers-list')
    soil_html = soil_html.replace('Leaf Preview', 'Soil Preview')
    soil_html = soil_html.replace('Scanned Leaf', 'Scanned Soil')
    soil_html = soil_html.replace('<!-- Disease Detection Section', '\n<!-- Soil Analyzer Section')

    # Create Fertilizer Section
    fert_html = disease_html.replace('Disease Detection Mode', 'Fertilizer OCR Mode')
    fert_html = fert_html.replace('disease-mode-section', 'fertilizer-mode-section')
    fert_html = fert_html.replace('fa-microscope', 'fa-flask-vial')
    fert_html = fert_html.replace('Detect Crop Diseases', 'Read Fertilizer Labels')
    fert_html = fert_html.replace('Upload a photo of a crop leaf and our AI will instantly identify the disease', 'Upload a photo of any chemical or fertilizer bottle line and AI will explain its exact usage')
    fert_html = fert_html.replace('drop-zone', 'fert-drop-zone')
    fert_html = fert_html.replace('upload-form', 'fert-upload-form')
    fert_html = fert_html.replace('file-input', 'fert-file-input')
    fert_html = fert_html.replace('default-state', 'fert-default-state')
    fert_html = fert_html.replace('preview-state', 'fert-preview-state')
    fert_html = fert_html.replace('image-preview', 'fert-image-preview')
    fert_html = fert_html.replace('remove-btn', 'fert-remove-btn')
    fert_html = fert_html.replace('analyze-btn', 'fert-analyze-btn')
    fert_html = fert_html.replace('loading-overlay', 'fert-loading-overlay')
    fert_html = fert_html.replace('loading-status-text', 'fert-loading-status-text')
    fert_html = fert_html.replace('results-section', 'fert-results-section')
    fert_html = fert_html.replace('Scan New Leaf', 'Scan New Label')
    fert_html = fert_html.replace('scan-new-btn', 'fert-scan-new-btn')
    fert_html = fert_html.replace('result-card-image', 'fert-result-card-image')
    fert_html = fert_html.replace('result-image', 'fert-result-image')
    fert_html = fert_html.replace('conf-value', 'fert-conf-value')
    fert_html = fert_html.replace('conf-bar', 'fert-conf-bar')
    fert_html = fert_html.replace('health-score', 'fert-health-score')
    fert_html = fert_html.replace('Plant Health Score', 'Safety Rating')
    fert_html = fert_html.replace('data-card', 'fert-data-card')
    fert_html = fert_html.replace('disease-name', 'fert-type-name')
    fert_html = fert_html.replace('crop-tag', 'fert-crop-tag')
    fert_html = fert_html.replace('scientific-name', 'fert-scientific-name')
    fert_html = fert_html.replace('severity-badge', 'fert-severity-badge')
    fert_html = fert_html.replace('Drag & Drop Leaf Image', 'Drag & Drop Label Image')
    fert_html = fert_html.replace('<span class="mode-label">', '<span class="mode-label mode-label-purple">')
    fert_html = fert_html.replace('Symptoms', 'Active Ingredients')
    fert_html = fert_html.replace('symptoms-text', 'fert-ingredients-text')
    fert_html = fert_html.replace('Causes', 'Usage Instructions')
    fert_html = fert_html.replace('causes-text', 'fert-usage-text')
    fert_html = fert_html.replace('Prevention', 'Safety Precautions')
    fert_html = fert_html.replace('prevention-text', 'fert-safety-text')
    fert_html = fert_html.replace('Treatment & Best Practices', 'Target Crops & Pests')
    fert_html = fert_html.replace('treatment-text', 'fert-targets-text')
    fert_html = fert_html.replace('Recommended Chemical Control', 'Expert Recommendations')
    fert_html = fert_html.replace('chemicals-list', 'fert-recommendations-list')
    fert_html = fert_html.replace('Leaf Preview', 'Label Preview')
    fert_html = fert_html.replace('Scanned Leaf', 'Scanned Label')
    fert_html = fert_html.replace('<!-- Disease Detection Section', '\n<!-- Fertilizer OCR Section')

    new_html = html.replace(disease_html, disease_html + soil_html + fert_html)
    
    with open('templates/index.html', 'w', encoding='utf-8') as f:
        f.write(new_html)
        
    print('SUCCESS')
else:
    print('FAILED')
